// <auto-generated />
using System;
using CourseAI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseAI.Migrations
{
    [DbContext(typeof(CourseAIDbContext))]
    [Migration("20251126215323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CourseAI.Models.KnownSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningProfileId");

                    b.ToTable("KnownSkills");
                });

            modelBuilder.Entity("CourseAI.Models.LearningProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("KnownSkills")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LearningGoal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredLearningStyles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.HasKey("Id");

                    b.ToTable("LearningProfiles");
                });

            modelBuilder.Entity("CourseAI.Models.LearningResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoadmapModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapModuleId");

                    b.ToTable("LearningResources");
                });

            modelBuilder.Entity("CourseAI.Models.PreferredLearningStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningProfileId");

                    b.ToTable("PreferredLearningStyles");
                });

            modelBuilder.Entity("CourseAI.Models.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LearningProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Modules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LearningProfileId");

                    b.ToTable("Roadmaps");
                });

            modelBuilder.Entity("CourseAI.Models.RoadmapConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoadmapTopicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapTopicId");

                    b.ToTable("RoadmapConcepts");
                });

            modelBuilder.Entity("CourseAI.Models.RoadmapModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("EstimatedDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.ToTable("RoadmapModules");
                });

            modelBuilder.Entity("CourseAI.Models.RoadmapTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Concepts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfidenceScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoadmapModuleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapModuleId");

                    b.ToTable("RoadmapTopics");
                });

            modelBuilder.Entity("CourseAI.Models.KnownSkill", b =>
                {
                    b.HasOne("CourseAI.Models.LearningProfile", "LearningProfile")
                        .WithMany()
                        .HasForeignKey("LearningProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningProfile");
                });

            modelBuilder.Entity("CourseAI.Models.LearningResource", b =>
                {
                    b.HasOne("CourseAI.Models.RoadmapModule", "RoadmapModule")
                        .WithMany()
                        .HasForeignKey("RoadmapModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadmapModule");
                });

            modelBuilder.Entity("CourseAI.Models.PreferredLearningStyle", b =>
                {
                    b.HasOne("CourseAI.Models.LearningProfile", "LearningProfile")
                        .WithMany()
                        .HasForeignKey("LearningProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningProfile");
                });

            modelBuilder.Entity("CourseAI.Models.Roadmap", b =>
                {
                    b.HasOne("CourseAI.Models.LearningProfile", "LearningProfile")
                        .WithMany("Roadmaps")
                        .HasForeignKey("LearningProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningProfile");
                });

            modelBuilder.Entity("CourseAI.Models.RoadmapConcept", b =>
                {
                    b.HasOne("CourseAI.Models.RoadmapTopic", "RoadmapTopic")
                        .WithMany()
                        .HasForeignKey("RoadmapTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadmapTopic");
                });

            modelBuilder.Entity("CourseAI.Models.RoadmapModule", b =>
                {
                    b.HasOne("CourseAI.Models.Roadmap", "Roadmap")
                        .WithMany()
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roadmap");
                });

            modelBuilder.Entity("CourseAI.Models.RoadmapTopic", b =>
                {
                    b.HasOne("CourseAI.Models.RoadmapModule", "RoadmapModule")
                        .WithMany()
                        .HasForeignKey("RoadmapModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoadmapModule");
                });

            modelBuilder.Entity("CourseAI.Models.LearningProfile", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
